// fixtures/apps/react-sample/src/pages/Home.tsx
import { useEffect, useState } from 'react';
import { get, login } from '../api';

export function Home() {
  const [me, setMe] = useState<{ name?: string } | null>(null);

  useEffect(() => {
    void (async () => {
      await login();
      setMe(await get<{ name: string }>('/api/me'));
    })();
  }, []);

  return <main><h1>Home</h1><p>{me?.name ?? 'loading'}</p></main>;
}

// fixtures/apps/vue-sample/src/pages/Home.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { get, login } from '../api';

const me = ref<{ name?: string } | null>(null);
onMounted(async () => {
  await login();
  me.value = await get<{ name: string }>('/api/me');
});
</script>

<template><main><h1>Home</h1><p>{{ me?.name ?? 'loading' }}</p></main></template>
