// fixtures/apps/react-sample/src/pages/Stats.tsx
import { useEffect, useState } from 'react';
import { get } from '../api';

export default function Stats() {
  const [stats, setStats] = useState<Record<string, unknown> | null>(null);
  useEffect(() => {
    void get<Record<string, unknown>>('/api/stats').then(setStats);
  }, []);
  return <main><h1>Stats</h1><pre>{JSON.stringify(stats, null, 2)}</pre></main>;
}

// fixtures/apps/vue-sample/src/pages/Stats.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { get } from '../api';

const stats = ref<Record<string, unknown> | null>(null);
onMounted(async () => {
  stats.value = await get<Record<string, unknown>>('/api/stats');
});
</script>

<template><main><h1>Stats</h1><pre>{{ JSON.stringify(stats, null, 2) }}</pre></main></template>
