// fixtures/apps/react-sample/src/pages/UserDetail.tsx
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { get } from '../api';

export default function UserDetail() {
  const { id } = useParams();
  const [user, setUser] = useState<{ name?: string } | null>(null);
  useEffect(() => {
    void get<{ name: string }>(`/api/users/${id}`).then(setUser);
  }, [id]);
  return <main><h1>User {id}</h1><p>{user?.name ?? 'loading'}</p></main>;
}

// fixtures/apps/vue-sample/src/pages/UserDetail.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute } from 'vue-router';
import { get } from '../api';

const route = useRoute();
const user = ref<{ name?: string } | null>(null);
onMounted(async () => {
  user.value = await get<{ name: string }>(`/api/users/${route.params.id}`);
});
</script>

<template><main><h1>User {{ route.params.id }}</h1><p>{{ user?.name ?? 'loading' }}</p></main></template>
