// fixtures/apps/react-sample/src/pages/Users.tsx
import { useEffect, useState } from 'react';
import { get } from '../api';

interface User { id: number; name: string }

export default function Users() {
  const [users, setUsers] = useState<User[]>([]);
  useEffect(() => {
    void get<{ users: User[] }>('/api/users').then((r) => setUsers(r.users));
  }, []);
  return <main><h1>Users</h1><ul>{users.map((u) => <li key={u.id}>{u.name}</li>)}</ul></main>;
}

// fixtures/apps/vue-sample/src/pages/Users.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { get } from '../api';

const users = ref<Array<{ id: number; name: string }>>([]);
onMounted(async () => {
  users.value = (await get<{ users: Array<{ id: number; name: string }> }>('/api/users')).users;
});
</script>

<template><main><h1>Users</h1><ul><li v-for="u in users" :key="u.id">{{ u.name }}</li></ul></main></template>
